# Generated by Django 2.2.6 on 2019-10-21 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sundayleagueApp', '0003_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.IntegerField()),
                ('match_played', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('draws', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('goals_for', models.IntegerField()),
                ('goals_against', models.IntegerField()),
                ('points', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sundayleagueApp.Team', unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='file',
            name='file_name',
        ),
        migrations.AddField(
            model_name='file',
            name='already_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='round_number',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='match',
            name='first_team_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='second_team_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
