# Generated by Django 2.2.6 on 2019-10-21 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sundayleagueApp', '0004_auto_20191021_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablerow',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sundayleagueApp.Team'),
        ),
    ]
