# Generated by Django 2.2.6 on 2019-10-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sundayleagueApp', '0005_auto_20191021_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablerow',
            name='draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tablerow',
            name='goals_against',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tablerow',
            name='goals_for',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tablerow',
            name='league',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tablerow',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tablerow',
            name='match_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tablerow',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tablerow',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
