# Generated by Django 2.2.6 on 2019-10-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sundayleagueApp', '0006_auto_20191021_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.IntegerField(default=0),
        ),
    ]
