# Generated by Django 2.2.6 on 2019-10-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sundayleagueApp', '0007_auto_20191021_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='round_number',
        ),
        migrations.AddField(
            model_name='file',
            name='is_fixture',
            field=models.BooleanField(default=False),
        ),
    ]
