# Generated by Django 2.2.6 on 2020-03-05 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sundayleagueApp', '0010_auto_20200301_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_surrendered',
            field=models.BooleanField(default=False),
        ),
    ]
