# Generated by Django 2.2.6 on 2020-03-06 19:50

from django.db import migrations, models
import django.db.models.deletion
import sundayleagueApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('sundayleagueApp', '0012_auto_20200305_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[(sundayleagueApp.models.PlayerPosition('GK'), 'GK'), (sundayleagueApp.models.PlayerPosition('DEF'), 'DEF'), (sundayleagueApp.models.PlayerPosition('MID'), 'MID'), (sundayleagueApp.models.PlayerPosition('FWD'), 'FWD')], default=sundayleagueApp.models.PlayerPosition('GK'), max_length=3)),
                ('first_name', models.CharField(max_length=255)),
                ('family_name', models.CharField(max_length=255)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sundayleagueApp.Team')),
            ],
        ),
    ]
