# Generated by Django 2.2.6 on 2020-05-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sundayleagueApp', '0020_systemsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='key',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
