# Generated by Django 2.2.6 on 2020-05-28 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sundayleagueApp', '0022_auto_20200526_1813'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemSetting',
        ),
    ]
