# Generated by Django 2.2.6 on 2020-08-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sundayleagueApp', '0024_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='info',
            field=models.CharField(max_length=2055),
        ),
    ]
