# Generated by Django 2.2.6 on 2020-08-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sundayleagueApp', '0025_auto_20200823_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='info',
            field=models.TextField(max_length=2055),
        ),
    ]
