# Generated by Django 2.2.6 on 2021-02-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sundayleagueApp', '0029_profile_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='first_team_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='second_team_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
