# Generated by Django 3.1.6 on 2021-03-06 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sundayleagueApp', '0031_match_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Najavljena'), ('LIVE', 'V živo'), ('COMPLETED', 'Zaključena'), ('CONFIRMED', 'Potrjena')], default='NOT_STARTED', max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sundayleagueApp.team'),
        ),
    ]
