# Generated by Django 3.1.6 on 2021-03-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sundayleagueApp', '0032_auto_20210306_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='info',
            field=models.TextField(max_length=8191),
        ),
    ]
