# Generated by Django 3.1.6 on 2021-04-09 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sundayleagueApp', '0033_auto_20210331_1634'),
        ('sundayleagueApp', '0033_systemsetting'),
    ]

    operations = [
    ]
